FROM node@sha256:d6aa754f16b3197301076f047b5def2f02ea1dbbc2ca920407d46d7ec7f87b20 AS node
FROM python@sha256:0a310eeecf4e1f5a0743f9a6520c90c88d089c903ca5fd283f501e3a805f5f89
COPY --from=node /usr/local/bin/node /usr/local/bin/node
COPY --from=node /usr/local/lib/node_modules/npm /usr/local/lib/node_modules/npm
RUN ln -s /usr/local/lib/node_modules/npm/bin/npm-cli.js /usr/local/bin/npm
COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt
WORKDIR /consumer
COPY package.json package-lock.json flowdoc-core.tgz ./
RUN npm ci --ignore-scripts --no-audit --no-fund
COPY checkResources.mjs ./
RUN mkdir /consumer/temp && chown -R 10001:10001 /consumer
USER 10001:10001
CMD ["node","checkResources.mjs"]
