import assert from 'node:assert/strict';
import {readFile,writeFile,readdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {validateTemplate,prepareGeneration,composeDocument,loadBundledResources,createPdfEngine} from '@flowdoc/core';
const unwrap=r=>{assert.equal(r.ok,true,JSON.stringify(r));return r.value;};
const load=async name=>JSON.parse(await readFile(`/consumer/${name}.json`,'utf8'));
const resources=unwrap(await loadBundledResources({pythonExecutable:'/usr/local/bin/python',tempRoot:'/consumer/temp'}));
const engine=unwrap(await createPdfEngine(resources));
const srs=unwrap(validateTemplate(await readFile('/consumer/srs-template.json','utf8')));
const srsInput=await load('srs-request'),srsPrepared=unwrap(prepareGeneration(srs,srsInput));
const graph=unwrap(composeDocument(srs,JSON.parse(JSON.stringify(srsPrepared))));
assert.deepEqual(graph.rootIds,['content-0~note','content-1~table','content-2~note']);
assert.deepEqual(graph.nodes['content-1~table'].rowIds,['content-1~header','content-1~row~item-0']);
assert.equal(graph.nodes['content-1~rtr~item-0'].children[0].text,'ไม่ระบุ');
const ids=Object.values(graph.nodes).flatMap(n=>[n.id,...n.type==='text-block'?n.children.map(c=>c.id):[]]);
assert.equal(new Set(ids).size,ids.length);assert.deepEqual(Object.keys(graph.sourceMap).sort(),ids.sort());
const rejected=await engine.generatePdf(graph);assert.equal(rejected.ok,false);assert.equal(rejected.issues[0].code,'LAYOUT_FAILED');
const template=unwrap(validateTemplate(await readFile('/consumer/binding-template.json','utf8')));
const input=await load('binding-request'),before=JSON.stringify(input);
const prepared=unwrap(prepareGeneration(template,input));assert.equal(prepared.warnings.length,1);assert.equal(prepared.warnings[0].code,'UNKNOWN_VARIABLE');
const composed=composeDocument(template,JSON.parse(JSON.stringify(prepared))),document=unwrap(composed);
assert.equal(composed.warnings[0].code,'UNKNOWN_VARIABLE');assert.equal(JSON.stringify(input),before);
const bad=structuredClone(input);delete bad.data.projectName;const invalid=prepareGeneration(template,bad);assert.equal(invalid.ok,false);assert.ok(invalid.issues.some(i=>i.code==='MISSING_REQUIRED'));assert.equal('value' in invalid,false);
const pdf=unwrap(await engine.generatePdf(document));assert.equal(pdf.pageCount,1);
const expected=['โครงการ FlowDoc ทดสอบการแทนตัวแปร: ขอบเขตการทำงาน','สร้างเอกสารจากโครงและข้อมูล','หมายเหตุ: ไม่ได้ระบุหมายเหตุ','โครงการ FlowDoc ทดสอบการแทนตัวแปร: รายการสุดท้ายใช้โครงเดิมและข้อมูลคนละชุด'].join('\n');
const actual=document.rootIds.map(id=>document.nodes[id].children.map(c=>c.type==='text'?c.text:'\n').join('')).join('\n');assert.equal(actual,expected);
await writeFile('/consumer/output/bound-text.pdf',pdf.bytes);await writeFile('/consumer/output/bound-text.expected.txt',expected);
await writeFile('/consumer/output/srs.composed.json',JSON.stringify(graph,null,2));
await writeFile('/consumer/output/binding.prepared.json',JSON.stringify(prepared,null,2));
assert.deepEqual(await readdir('/consumer/temp'),[]);
const result={status:'PASS',pageCount:pdf.pageCount,bytes:pdf.bytes.length,sha256:createHash('sha256').update(pdf.bytes).digest('hex'),checks:['installed root APIs','raw template registration','A/B/A table graph','default binding','unique IDs and complete sourceMap','table rendering rejected','JSON persisted prepared input','global/local text A/B/A PDF','newline binding','warnings excluded','required input rejected','immutable request','temp cleanup']};
await writeFile('/consumer/output/binding-result.json',JSON.stringify(result,null,2)+'\n');
