import {it,expect} from 'vitest';
import {coverTemplate} from '../helpers/cover.js';
import {composed} from '../helpers/sections.js';
import {fakeRuntime} from '../helpers/document.js';
import {documentFlow} from '../../src/layout/documentFlow.js';
import {collectContents} from '../../src/composition/contents.js';
import {indexDestinations,resolveLinkGeometry} from '../../src/layout/linkGeometry.js';
import {fillContentsNumbers} from '../../src/layout/fillContentsNumbers.js';
import {appendPageNumbers} from '../../src/layout/pageNumbers.js';
it('excludes cover headings while preserving anchors and uses one counted number for TOC and footer',async()=>{
 const t=coverTemplate();Object.assign(t.sections[0].source.fragment.nodes.title.props,{anchorId:'cover',toc:{level:1}});
 t.sections.splice(1,0,{id:'toc',source:{kind:'authored',repeats:[],fragment:{rootIds:['toc'],nodes:{toc:{id:'toc',type:'table-of-contents',props:{textStyleId:'body'}}}}}},{id:'blank',source:{kind:'blank'}});
 Object.assign(t.formats['section-note'].fragment.nodes.note.props,{anchorId:'body',toc:{level:1}});
 t.formats['section-note'].fragment.nodes.note.children.push({id:'back',type:'reference',text:'Back',target:'cover'});
 const d=composed(t),draw=await documentFlow(d,fakeRuntime),anchors=indexDestinations(d,draw);
 expect(collectContents(d).map(e=>e.anchorId)).toEqual(['body']);expect(anchors.cover?.pageIndex).toBe(0);expect(anchors.body?.pageIndex).toBe(3);
 await fillContentsNumbers(draw,anchors,fakeRuntime);await appendPageNumbers(d,draw,fakeRuntime);resolveLinkGeometry(d,draw,anchors);
 expect(draw.pages.map(p=>p.countedPageNumber)).toEqual([null,1,2,3]);
 expect(draw.pages[0]!.commands.some(c=>c.id.startsWith('page-number'))).toBe(false);expect(draw.pages[2]!.commands).toEqual([]);
 expect(draw.pages[1]!.commands.find(c=>c.id==='contents-number-0')?.text).toBe('3');expect(draw.pages[3]!.commands.find(c=>c.id==='page-number-3')?.text).toBe('3');
 expect(draw.pages[3]!.annotations?.some(a=>a.destination.type==='internal'&&a.destination.target==='cover')).toBe(true);
});
