import {it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {validateTemplate,prepareGeneration,composeDocument} from '../../src/index.js';
import {documentFlow} from '../../src/layout/documentFlow.js';
import {fakeRuntime,document} from '../helpers/document.js';
import {textFlow} from '../../src/layout/textFlow.js';
import {validateResolvedDocument} from '../../src/composition/validateResolvedDocument.js';
export function tableDoc(lines=3){const t=JSON.parse(readFileSync('fixtures/srs-basic/template.json','utf8'));t.examples=[];t.styles.body.lineHeightPt=20;const v=validateTemplate(t);if(!v.ok)throw Error('template');const p=prepareGeneration(v.value,{docKey:t.docKey,data:{projectName:'test'},content:[{format:'requirement-list',data:{items:[{code:'R1',detail:Array.from({length:lines},(_,i)=>`L${i}`).join('\n'),remark:'OK'}]}}]});if(!p.ok)throw Error('prepare');const r=composeDocument(v.value,p.value);if(!r.ok)throw Error('compose');return r.value;}
const body=(draw:any)=>draw.pages.flatMap((p:any)=>p.commands).filter((c:any)=>c.nodeId==='content-0~rtd~item-0');
it('retains text-only drawing byte-for-byte',async()=>{const d=document();expect(await documentFlow(d,fakeRuntime)).toEqual(await textFlow(d,fakeRuntime));});
it('accepts composed tables and draws one short row with borders',async()=>{const d=tableDoc();expect(validateResolvedDocument(d)).toEqual([]);const r=await documentFlow(d,fakeRuntime);expect(r.pages).toHaveLength(1);expect(r.pages[0]!.borders!.length).toBeGreaterThan(0);expect(body(r).map((c:any)=>c.text)).toEqual(['ระบบต้อง L0','L1','L2']);});
it('continues long row without duplicated cell values and repeats header',async()=>{const r=await documentFlow(tableDoc(90),fakeRuntime);expect(r.pages.length).toBeGreaterThan(2);expect(body(r)).toHaveLength(90);expect(body(r).map((c:any)=>c.text)).toEqual(Array.from({length:90},(_,i)=>i?'L'+i:'ระบบต้อง L0'));for(const page of r.pages){expect(page.commands.some(c=>c.nodeId==='content-0~htc')).toBe(true);expect(page.commands.some(c=>c.nodeId==='content-0~rtd~item-0')).toBe(true);}expect(r.pages.flatMap(p=>p.commands).filter(c=>c.text==='R1')).toHaveLength(1);expect(new Set(r.pages.flatMap(p=>p.commands.map(c=>c.id))).size).toBe(r.pages.flatMap(p=>p.commands).length);});
it('supports no repeated header and header-only empty table',async()=>{const d=tableDoc(50),t:any=d.nodes['content-0~table'];t.props.repeatHeaderRows=false;const r=await documentFlow(d,fakeRuntime);expect(r.pages[1]!.commands.some(c=>c.nodeId==='content-0~htc')).toBe(false);t.rowIds=['content-0~header'];const empty=await documentFlow(d,fakeRuntime);expect(empty.pages).toHaveLength(1);expect(empty.pages[0]!.commands).toHaveLength(3);});
it('moves header with first body line rather than leaving it at page bottom',async()=>{const d=tableDoc(3),pre:any=document(Array(35).fill('before').join('\n'));d.nodes.t=pre.nodes.t;d.sourceMap.t=pre.sourceMap.t;d.rootIds.unshift('t');const r=await documentFlow(d,fakeRuntime);expect(r.pages[0]!.commands.every(c=>c.nodeId==='t')).toBe(true);expect(r.pages[1]!.commands[0]!.nodeId).toBe('content-0~htc');});
it('flows following text and another table after current table',async()=>{const d=tableDoc(4),post:any=document('after');d.nodes.t=post.nodes.t;d.sourceMap.t=post.sourceMap.t;d.rootIds.push('t','content-0~table');const r=await documentFlow(d,fakeRuntime);const commands=r.pages[0]!.commands;const after=commands.find(c=>c.text==='after')!;expect(after.bounds.yPt).toBeGreaterThan(body(r)[3].bounds.yPt);expect(commands.at(-1)!.bounds.yPt).toBeGreaterThan(after.bounds.yPt);});
it('supports multiple TextBlocks and mixed line heights in cells',async()=>{const d=tableDoc(50);d.styles.tall={...d.styles.body!,lineHeightPt:35};const c:any=d.nodes['content-0~rc~item-0'];d.nodes.extra={id:'extra',type:'text-block',role:{role:'paragraph'},props:{textStyleId:'tall'},children:[{id:'extra-leaf',type:'text',text:Array(30).fill('more').join('\n')}]};c.childIds.push('extra');const r=await documentFlow(d,fakeRuntime);expect(r.pages.flatMap(p=>p.commands).filter(c=>c.nodeId==='extra')).toHaveLength(30);for(const p of r.pages)for(const c of p.commands)expect(c.bounds.yPt+c.bounds.heightPt).toBeLessThanOrEqual(p.heightPt-20*72/25.4+0.001);});
it('moves unbreakable row intact and rejects one taller than a page',async()=>{const d=tableDoc(10),row:any=d.nodes['content-0~row~item-0'];row.props.allowBreak=false;const pre:any=document(Array(30).fill('before').join('\n'));d.nodes.t=pre.nodes.t;d.rootIds.unshift('t');const r=await documentFlow(d,fakeRuntime);expect(r.pages[0]!.commands.every(c=>c.nodeId==='t')).toBe(true);expect(body(r)).toHaveLength(10);const huge=tableDoc(90);(huge.nodes['content-0~row~item-0'] as any).props.allowBreak=false;await expect(documentFlow(huge,fakeRuntime)).rejects.toThrow(/row/i);});
it.each(['width','line','header','grapheme'])('rejects impossible %s instead of looping or clipping',async kind=>{const d=tableDoc();if(kind==='width')(d.nodes['content-0~table'] as any).columns[0].width.value=300;else if(kind==='line')d.styles.body!.lineHeightPt=800;else if(kind==='header')(d.nodes['content-0~htc'] as any).children[0].text=Array(100).fill('H').join('\n');else (d.nodes['content-0~table'] as any).columns[0].width={value:9,unit:'pt'};await expect(documentFlow(d,fakeRuntime)).rejects.toThrow();});
