import {it,expect} from 'vitest';
import {bandTemplate} from '../helpers/bands.js';
import {fakeRuntime} from '../helpers/document.js';
import {validateTemplate} from '../../src/template/validateTemplate.js';
import {prepareGeneration} from '../../src/data/prepareGeneration.js';
import {composeDocument} from '../../src/composition/composeDocument.js';
import {documentFlow} from '../../src/layout/documentFlow.js';
function doc(mode='all',lines=80):any {const t=bandTemplate();t.sections=[t.sections[0]];t.sections[0].headerMode=mode;t.sections[0].source.fragment.nodes.title.children=[{id:'text',type:'text',text:Array(lines).fill('BODY').join('\n')}];t.styles.body.lineHeightPt=20;const v=validateTemplate(t);if(!v.ok)throw Error(JSON.stringify(v));const p=prepareGeneration(v.value,{docKey:t.docKey,data:{projectName:'BODY'},header:{projectName:'HEAD'},footer:{projectName:'FOOT'},content:[]});if(!p.ok)throw Error(JSON.stringify(p));const d=composeDocument(v.value,p.value);if(!d.ok)throw Error(JSON.stringify(d));return d.value;}
it('repeats bands without overlapping body and changes first/continuation budgets',async()=>{for(const mode of ['all','first','continuation','none']){const d=doc(mode),draw=await documentFlow(d,fakeRuntime);expect(draw.pages.length).toBeGreaterThan(1);for(const [i,p] of draw.pages.entries()){const head=mode==='all'||mode==='first'&&i===0||mode==='continuation'&&i>0;expect(p.commands.filter(c=>c.text==='HEAD')).toHaveLength(head?1:0);const footer=p.commands.find(c=>c.text==='FOOT')!;expect(footer).toBeDefined();const body=p.commands.filter(c=>c.text==='BODY');expect(body[0]!.bounds.yPt).toBeCloseTo(20*72/25.4+(head?20:0));expect(body.at(-1)!.bounds.yPt+20).toBeLessThanOrEqual(footer.bounds.yPt+1e-6);}}});
it('caps aggregate height at 40 percent, ignores cover and blank bands',async()=>{const d=doc('all',1),inner=(297-40)*72/25.4;d.header.sizing={mode:'fixed',height:{value:inner*.4-20,unit:'pt'}};await expect(documentFlow(d,fakeRuntime)).resolves.toBeDefined();d.header.sizing.height.value+=1;await expect(documentFlow(d,fakeRuntime)).rejects.toBeDefined();d.sections[0].role='cover';await expect(documentFlow(d,fakeRuntime)).resolves.toBeDefined();const draw=await documentFlow(d,fakeRuntime);expect(draw.pages[0]!.commands.map(c=>c.text)).toEqual(['BODY']);d.sections[0].role='body';d.sections[0].sourceKind='blank';d.sections[0].rootIds=[];d.rootIds=[];expect((await documentFlow(d,fakeRuntime)).pages[0]!.commands).toEqual([]);});
it('moves a protected row to the larger continuation region and terminates impossible rows',async()=>{const d=doc('first',1);delete d.footer;d.header.sizing={mode:'fixed',height:{value:200,unit:'pt'}};const old=d.rootIds[0];const p=d.nodes[old];p.children=[{id:'txt',type:'text',text:Array(30).fill('ROW').join('\n')}];d.nodes.row={id:'row',type:'table-row',props:{allowBreak:false},cellIds:['cell']};d.nodes.cell={id:'cell',type:'table-cell',props:{},childIds:[old]};d.nodes.table={id:'table',type:'table',props:{headerRowCount:0,repeatHeaderRows:false},columns:[{width:{value:150,unit:'pt'}}],rowIds:['row']};d.rootIds=['table'];d.sections[0].rootIds=['table'];const draw=await documentFlow(d,fakeRuntime);expect(draw.pages).toHaveLength(2);expect(draw.pages[0]!.commands.map(c=>c.text)).toEqual(['HEAD']);expect(draw.pages[1]!.commands.filter(c=>c.text==='ROW')).toHaveLength(30);p.children[0].text=Array(50).fill('ROW').join('\n');await expect(documentFlow(d,fakeRuntime)).rejects.toBeDefined();});
it('splits table lines into the smaller continuation region without loss or overlap',async()=>{const d=doc('continuation',1);d.header.sizing={mode:'fixed',height:{value:120,unit:'pt'}};const old=d.rootIds[0],p=d.nodes[old];p.children=[{id:'txt',type:'text',text:Array(100).fill('ROW').join('\n')}];d.nodes.row={id:'row',type:'table-row',props:{allowBreak:true},cellIds:['cell']};d.nodes.cell={id:'cell',type:'table-cell',props:{},childIds:[old]};d.nodes.table={id:'table',type:'table',props:{headerRowCount:0,repeatHeaderRows:false},columns:[{width:{value:150,unit:'pt'}}],rowIds:['row']};d.rootIds=['table'];d.sections[0].rootIds=['table'];const draw=await documentFlow(d,fakeRuntime);expect(draw.pages.flatMap(p=>p.commands).filter(c=>c.text==='ROW')).toHaveLength(100);for(const [i,p] of draw.pages.entries()){const lines=p.commands.filter(c=>c.text==='ROW');expect(lines[0]!.bounds.yPt).toBeGreaterThanOrEqual(20*72/25.4+(i?120:0));expect(lines.at(-1)!.bounds.yPt+20).toBeLessThanOrEqual(p.commands.find(c=>c.text==='FOOT')!.bounds.yPt);}});
