import {it,expect} from 'vitest';
import {measurePageBand,selectPageBands} from '../../src/layout/pageBands.js';
import {fakeRuntime} from '../helpers/document.js';
const style:any={body:{fontFamilyKey:'sarabun',fontWeight:'normal',fontSize:{value:12,unit:'pt'},lineHeightPt:20}};
const band=(text='one'):any=>({baseTextStyleId:'body',sourceMap:{},rootIds:['a'],nodes:{a:{id:'a',type:'text-block',role:{role:'paragraph'},props:{textStyleId:'body'},children:[{id:'txt',type:'text',text}]}}});
it('measures minimum, real content, min and fixed heights without shrinking',async()=>{expect((await measurePageBand(band(''),style,100,fakeRuntime,{})).heightPt).toBe(20);const b=band('a\nb');expect((await measurePageBand(b,style,100,fakeRuntime,{})).heightPt).toBe(40);b.sizing={mode:'fixed',height:{value:30,unit:'pt'}};await expect(measurePageBand(b,style,100,fakeRuntime,{})).rejects.toBeDefined();b.sizing={mode:'content',minHeight:{value:60,unit:'pt'}};expect((await measurePageBand(b,style,100,fakeRuntime,{})).heightPt).toBe(60);b.sizing.maxHeight={value:30,unit:'pt'};await expect(measurePageBand(b,style,100,fakeRuntime,{})).rejects.toBeDefined();});
it('stacks within columns and uses maximum column height',async()=>{const b=band();b.nodes.b={...structuredClone(b.nodes.a),id:'b',children:[{id:'btxt',type:'text',text:'x\ny'}]};b.nodes.c={id:'c',type:'columns',props:{gap:{value:10,unit:'pt'}},columns:[{weight:1,childIds:['a']},{weight:2,childIds:['b']}]};b.rootIds=['c'];const m=await measurePageBand(b,style,100,fakeRuntime,{});expect(m.heightPt).toBe(40);expect(m.commands.find(x=>x.text==='x')!.bounds.xPt).toBe(40);await expect(measurePageBand(b,style,5,fakeRuntime,{})).rejects.toBeDefined();});
it('keeps image frame height even when missing, contains images inside frame',async()=>{const b=band();b.nodes={pic:{id:'pic',type:'image',props:{width:{value:40,unit:'pt'},height:{value:30,unit:'pt'},align:'right',resourceId:'r'}}};b.rootIds=['pic'];const empty=await measurePageBand(b,style,100,fakeRuntime,{});expect(empty.heightPt).toBe(30);expect(empty.images).toEqual([]);const m=await measurePageBand(b,style,100,fakeRuntime,{r:{width:100,height:100} as any});expect(m.images[0]).toMatchObject({xPt:65,yPt:0,widthPt:30,heightPt:30});});
it('selects by section physical index and excludes cover/blank',()=>{expect(selectPageBands({headerMode:'first',footerMode:'continuation'},'body',0)).toEqual({header:true,footer:false});expect(selectPageBands({headerMode:'first',footerMode:'continuation'},'body',1)).toEqual({header:false,footer:true});expect(selectPageBands({},'cover',0)).toEqual({header:false,footer:false});expect(selectPageBands({},'blank',0)).toEqual({header:false,footer:false});});
