import {it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {validateTemplate,prepareGeneration,composeDocument} from '../../src/index.js';
const ref='01a11aa0-c9e6-780a-ae76-834fad559f4d';
it('validates and preserves authored image alignment through composition',()=>{
 for(const align of ['left','center','right']){const t=fixture();t.formats.photo.fragment.nodes.picture.props.align=align;const v=validateTemplate(t);expect(v.ok).toBe(true);if(!v.ok)continue;const p=prepareGeneration(v.value,{docKey:t.docKey,data:{photo:ref},content:[{format:'photo',data:{}}]});expect(p.ok).toBe(true);if(!p.ok)continue;const d=composeDocument(v.value,p.value);expect(d.ok).toBe(true);if(d.ok)expect(Object.values(d.value.nodes)[0]).toMatchObject({props:{align}});}
 for(const align of ['justify','',null,42]){const t=fixture();t.formats.photo.fragment.nodes.picture.props.align=align;expect(validateTemplate(t).ok).toBe(false);}
});
function fixture(){const t=JSON.parse(readFileSync('fixtures/srs-basic/template.json','utf8'));t.nodeModelVersion=5;t.globalSchema={type:'object',fields:{photo:{type:'image',required:true}}};t.formats={photo:{inputSchema:{type:'object',fields:{}},fragment:{rootIds:['picture'],nodes:{picture:{id:'picture',type:'image',props:{width:{value:100,unit:'mm'},height:{value:60,unit:'mm'},source:{scope:'global',key:'photo'}}}}},repeats:[]}};t.examples=[];return t;}
it('binds a scoped image reference into a model 5 document',()=>{const t=fixture(),v=validateTemplate(t);expect(v.ok).toBe(true);if(!v.ok)return;const p=prepareGeneration(v.value,{docKey:t.docKey,data:{photo:ref},content:[{format:'photo',data:{}}]});expect(p.ok).toBe(true);if(!p.ok)return;const d=composeDocument(v.value,p.value);expect(d.ok).toBe(true);if(d.ok){expect(d.value.nodeModelVersion).toBe(5);expect(Object.values(d.value.nodes)[0]).toMatchObject({type:'image',props:{resourceId:ref}});}});
it('requires image types for image slots and rejects URL or Base64 as bound values',()=>{const t=fixture();const v=validateTemplate(t);expect(v.ok).toBe(true);if(!v.ok)return;for(const value of ['https://example.org/a.png','data:image/png;base64,AA==',123,null,''])expect(prepareGeneration(v.value,{docKey:t.docKey,data:{photo:value},content:[{format:'photo',data:{}}]}).ok).toBe(false);t.globalSchema.fields.photo.type='string';expect(validateTemplate(t).ok).toBe(false);});
it('keeps legacy model 4 strict and rejects image fields in row items',()=>{const t=fixture();t.nodeModelVersion=4;expect(validateTemplate(t).ok).toBe(false);t.nodeModelVersion=5;t.globalSchema.fields.rows={type:'array',items:{type:'object',fields:{image:{type:'image'}}}};expect(validateTemplate(t).ok).toBe(false);});
it('allows absent optional images and preserves distinct global/local scope',()=>{const t=fixture();t.globalSchema.fields.photo.required=false;t.formats.photo.inputSchema.fields.photo={type:'image',required:true};t.formats.photo.fragment.nodes.picture.props.source.scope='local';const v=validateTemplate(t);expect(v.ok).toBe(true);if(!v.ok)return;const p=prepareGeneration(v.value,{docKey:t.docKey,data:{},content:[{format:'photo',data:{photo:ref}}]});expect(p.ok).toBe(true);if(!p.ok)return;expect(p.value.data.photo).toBe('');expect(composeDocument(v.value,p.value).ok).toBe(true);});
