import {it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {validateTemplate,prepareGeneration,composeDocument} from '../../src/index.js';
const variants=[{type:'url',value:'https://example.com'},{type:'link',text:'เว็บไซต์',url:'https://example.com'},{type:'reference',text:'หัวข้อ',target:'heading'}];
function fixture(){const t=JSON.parse(readFileSync('fixtures/srs-basic/template.json','utf8'));t.nodeModelVersion=7;t.examples=[];t.globalSchema={type:'object',fields:{jump:{type:'link'},anchor:{type:'string'}}};t.formats={body:{inputSchema:{type:'object',fields:{}},repeats:[],fragment:{rootIds:['p'],nodes:{p:{id:'p',type:'text-block',role:{role:'paragraph'},props:{textStyleId:Object.keys(t.styles)[0],anchorId:'heading'},children:[{id:'label',type:'text',text:'Heading '},{id:'jump',type:'field-ref',scope:'global',key:'jump'}]}}}}};return t;}
function compose(t:any,data:any={},content=[{format:'body',data:{}}]){const v=validateTemplate(t);expect(v.ok,JSON.stringify(v)).toBe(true);if(!v.ok)throw Error('template');const p=prepareGeneration(v.value,{docKey:t.docKey,data,content});if(!p.ok)return p;return composeDocument(v.value,p.value);}
it('binds all link variants with preserved labels and destinations',()=>{for(const jump of variants){const r=compose(fixture(),{jump});expect(r.ok,JSON.stringify(r)).toBe(true);if(r.ok)expect((Object.values(r.value.nodes)[0] as any).children[1]).toMatchObject(jump);}});
it('supports literal commands and scoped string properties',()=>{const t=fixture();t.formats.body.fragment.nodes.p.props.anchorId={scope:'global',key:'anchor'};t.formats.body.inputSchema.fields.caption={type:'string',required:true};t.formats.body.fragment.nodes.p.children=[{id:'jump',type:'reference',text:{scope:'local',key:'caption'},target:{scope:'global',key:'anchor'}}];expect(compose(t,{anchor:'bound'},[{format:'body',data:{caption:'ไป'}}]).ok).toBe(true);});
it('omits absent optional links, uses valid defaults and rejects malformed supplied values',()=>{expect(compose(fixture()).ok).toBe(true);const t=fixture();t.globalSchema.fields.jump.default=variants[0];expect(compose(t).ok).toBe(true);for(const jump of ['',null,42,{}, {...variants[0],extra:true},{type:'url',value:'javascript:alert(1)'},{type:'url',value:'https://u:p@example.com'},{type:'url',value:'https://example.com\n'}])expect(compose(fixture(),{jump}).ok).toBe(false);t.globalSchema.fields.jump.default='';expect(validateTemplate(t).ok).toBe(false);});
it('rejects duplicate or missing anchors and legacy link graphs',()=>{expect(compose(fixture(),{jump:{type:'reference',text:'x',target:'missing'}}).ok).toBe(false);expect(compose(fixture(),{},[{format:'body',data:{}},{format:'body',data:{}}]).ok).toBe(false);for(const model of [4,5,6]){const t=fixture();t.nodeModelVersion=model;expect(validateTemplate(t).ok).toBe(false);}});

it('binds item links in repeated table rows and keeps independently named destinations',()=>{
 const t=JSON.parse(readFileSync('fixtures/srs-basic/template.json','utf8'));t.nodeModelVersion=7;t.examples=[];
 const f=t.formats['requirement-list'];f.inputSchema.fields.items.items.fields.detail={type:'link',required:true};
 for(const n of Object.values(f.fragment.nodes) as any[])if(n.type==='text-block'&&n.children.some((c:any)=>c.type==='field-ref'&&c.key==='detail'))n.props.anchorId={scope:'item',key:'code'};
 const v=validateTemplate(t);expect(v.ok,JSON.stringify(v)).toBe(true);if(!v.ok)return;
 const p=prepareGeneration(v.value,{docKey:t.docKey,data:{projectName:'test'},content:[{format:'requirement-list',data:{items:[{code:'a',detail:{type:'reference',text:'next',target:'b'}},{code:'b',detail:{type:'reference',text:'back',target:'a'}}]}}]});expect(p.ok,JSON.stringify(p)).toBe(true);if(!p.ok)return;
 const r=composeDocument(v.value,p.value);expect(r.ok,JSON.stringify(r)).toBe(true);if(r.ok)expect(Object.values(r.value.nodes).filter((n:any)=>n.props.anchorId).map((n:any)=>n.props.anchorId)).toEqual(['a','b']);
});
it('rejects required absence and undeclared scalar binding keys',()=>{const t=fixture();t.globalSchema.fields.jump.required=true;expect(compose(t).ok).toBe(false);t.formats.body.fragment.nodes.p.props.anchorId={scope:'global',key:'unknown'};expect(validateTemplate(t).ok).toBe(false);});
