import {describe,it,expect} from 'vitest';
import {validateTemplate} from '../../src/index.js';
import {areaTemplate} from '../helpers/areas.js';
describe('area authored contract',()=>{
 it('accepts model11 body cell and static subformat',()=>expect(validateTemplate(areaTemplate()).ok).toBe(true));
 it('accepts root placement',()=>{const t=areaTemplate(),f=t.formats.merged;f.fragment.nodes.a.childIds.pop();f.fragment.rootIds.push('placement');expect(validateTemplate(t).ok).toBe(true);});
 it.each([['old model',(t:any)=>t.nodeModelVersion=10],['missing owner',(t:any)=>t.areaFormats['format-001'].ownerAreaId='missing'],['duplicate key',(t:any)=>t.areaFormats['format-002'].key='description'],['no formats',(t:any)=>t.areaFormats={}],['no placement',(t:any)=>{delete t.formats.merged.fragment.nodes.placement;t.formats.merged.fragment.nodes.a.childIds.pop();}],['duplicate placement',(t:any)=>{const n=t.formats.merged.fragment.nodes;n.p2={id:'p2',type:'area',props:{areaId:'area-001'}};n.a.childIds.push('p2');}],['header',(t:any)=>{const n=t.formats.merged.fragment.nodes;n.a.childIds.pop();n.h.childIds.push('placement');}],['nested declaration',(t:any)=>t.areaFormats['format-002'].inputSchema.fields.x={type:'area',areaId:'nested'}],['duplicate area identity',(t:any)=>t.globalSchema.fields.x={type:'area',areaId:'area-001'}],['invalid default',(t:any)=>t.formats.merged.inputSchema.fields.details.default=[{format:'missing',data:{}}]]] as const)('rejects %s',(_,mutate)=>{const t=areaTemplate();mutate(t);expect(validateTemplate(t).ok).toBe(false);});
 it('accepts equal keys under distinct area owners',()=>{const t=areaTemplate(),f=t.formats.merged;f.inputSchema.fields.other={type:'area',areaId:'area-002'};f.fragment.nodes.p2={id:'p2',type:'area',props:{areaId:'area-002'}};f.fragment.rootIds.push('p2');t.areaFormats['format-003']={...structuredClone(t.areaFormats['format-001']),ownerAreaId:'area-002'};expect(validateTemplate(t).ok).toBe(true);});
 it('rejects local area placed in another format',()=>{const t=areaTemplate();t.formats.other=structuredClone(t.formats.merged);delete t.formats.other.inputSchema.fields.details;expect(validateTemplate(t).ok).toBe(false);});
 it('rejects scalar binding to area',()=>{const t=areaTemplate();t.formats.merged.fragment.nodes.at.children=[{id:'ref',type:'field-ref',scope:'local',key:'details'}];expect(validateTemplate(t).ok).toBe(false);});
 it('rejects area nested in array schema',()=>{const t=areaTemplate();t.formats.merged.inputSchema.fields.items={type:'array',items:{type:'object',fields:{x:{type:'area',areaId:'nested'}}}};expect(validateTemplate(t).ok).toBe(false);});
 it('validates defaults against selected subformat',()=>{const t=areaTemplate();t.formats.merged.inputSchema.fields.details.default=[{format:'notice',data:{}}];expect(validateTemplate(t).ok).toBe(true);t.formats.merged.inputSchema.fields.details.default=[{format:'description',data:{}}];expect(validateTemplate(t).ok).toBe(false);});
 it('rejects table roots in a cell but permits them at root',()=>{const t=areaTemplate();const f=t.areaFormats['format-003']={...structuredClone(t.formats.merged),key:'table',ownerAreaId:'area-001'};f.inputSchema.fields={};delete f.fragment.nodes.placement;f.fragment.nodes.a.childIds.pop();expect(validateTemplate(t).ok).toBe(false);t.formats.merged.fragment.nodes.a.childIds.pop();t.formats.merged.fragment.rootIds.push('placement');expect(validateTemplate(t).ok).toBe(true);});
});
