import {mergedDoc} from '../helpers/merged.js';
import {validateResolvedDocument} from '../../src/composition/validateResolvedDocument.js';
import {it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {validateTemplate,prepareGeneration,composeDocument} from '../../src/index.js';
import {collectContents} from '../../src/composition/contents.js';
function fixture(){const t=JSON.parse(readFileSync('fixtures/links/template.json','utf8'));t.nodeModelVersion=8;t.formats.section.fragment.nodes.heading.props.toc={level:1};t.formats.contents={inputSchema:{type:'object',fields:{}},repeats:[],fragment:{rootIds:['toc'],nodes:{toc:{id:'toc',type:'table-of-contents',props:{textStyleId:'body'}}}}};return t;}
function compose(t:any,content:any[]){const v=validateTemplate(t);expect(v.ok,JSON.stringify(v)).toBe(true);if(!v.ok)throw Error();const p=prepareGeneration(v.value,{docKey:t.docKey,data:{},content});expect(p.ok,JSON.stringify(p)).toBe(true);if(!p.ok)throw Error();return composeDocument(v.value,p.value);}
const section=(anchor:string,heading='same')=>({format:'section',data:{anchor,target:anchor,heading}});
it('collects bound titles once in document order, preserving duplicate display names',()=>{const r=compose(fixture(),[{format:'contents',data:{}},section('a',' A\r\n B '),section('b'),section('c')]);expect(r.ok,JSON.stringify(r)).toBe(true);if(r.ok)expect(collectContents(r.value).map(e=>[e.anchorId,e.title,e.level])).toEqual([['a','A B',1],['b','same',1],['c','same',1]]);});
it('supports three levels now, gates metadata to model 8 and requires destinations',()=>{for(const level of [1,2,3]){const t=fixture();t.formats.section.fragment.nodes.heading.props.toc.level=level;expect(validateTemplate(t).ok).toBe(true);}for(const level of [0,4,5,7,1.5,'2',null]){const t=fixture();t.formats.section.fragment.nodes.heading.props.toc.level=level;expect(validateTemplate(t).ok).toBe(false);}for(const version of [4,5,6,7]){const t=fixture();t.nodeModelVersion=version;expect(validateTemplate(t).ok).toBe(false);}const t=fixture();delete t.formats.section.fragment.nodes.heading.props.anchorId;expect(validateTemplate(t).ok).toBe(false);});
it('rejects composed duplicate contents and empty selected titles, allows empty entries',()=>{const t=fixture();expect(compose(t,[{format:'contents',data:{}},{format:'contents',data:{}}]).ok).toBe(false);const r=compose(t,[section('a',' \n ')]);expect(r.ok).toBe(false);const e=compose(t,[{format:'contents',data:{}}]);expect(e.ok).toBe(true);if(e.ok)expect(collectContents(e.value)).toEqual([]);});
it('uses visible link labels as titles and does not collect unmarked blocks',()=>{const t=fixture();t.formats.section.fragment.nodes.heading.children=[{id:'caption',type:'link',text:'หัวข้อ',url:'https://example.com'}];const r=compose(t,[section('a')]);expect(r.ok).toBe(true);if(r.ok)expect(collectContents(r.value).map(x=>x.title)).toEqual(['หัวข้อ']);});

it('preserves model 8 merged cells and images, collects authored cell headings only once',()=>{const d=mergedDoc(3);d.nodeModelVersion=8;for(const [id,level] of [['ht',1],['at',2],['bt',3]] as const){d.nodes[id].props.toc={level};d.nodes[id].props.anchorId=id;}d.nodes.image={id:'image',type:'image',props:{width:{value:20,unit:'pt'},height:{value:20,unit:'pt'},resourceId:''}};d.rootIds.push('image');d.sourceMap.image={contentIndex:0,format:'image',sourceId:'image'};expect(validateResolvedDocument(d)).toEqual([]);expect(collectContents(d).map(e=>e.nodeId)).toEqual(['ht','at','bt']);d.nodes.h.childIds=['toc'];d.nodes.toc={id:'toc',type:'table-of-contents',props:{textStyleId:'body'}};expect(validateResolvedDocument(d).length).toBeGreaterThan(0);});
