import {it,expect} from 'vitest';
import {sectionTemplate} from '../helpers/sections.js';
import {validateTemplate} from '../../src/template/validateTemplate.js';
import {prepareGeneration} from '../../src/data/prepareGeneration.js';
import {composeDocument} from '../../src/composition/composeDocument.js';
import {validatePreparedInput} from '../../src/composition/validatePreparedInput.js';
import {validateResolvedDocument} from '../../src/composition/validateResolvedDocument.js';
export function bandTemplate():any {const t=sectionTemplate();t.nodeModelVersion=14;for(const k of ['header','footer'])t[k]={baseTextStyleId:'body',inputSchema:{type:'object',fields:{projectName:{type:'string',required:true}}},fragment:structuredClone(t.sections[0].source.fragment)};return t;}
const request=(t:any)=>({docKey:t.docKey,data:{projectName:'BODY'},header:{projectName:'HEAD'},footer:{projectName:'FOOT'},content:[]});
it('binds identical keys in independent band scopes and survives JSON boundaries',()=>{const t=bandTemplate(),v=validateTemplate(t);expect(v.ok,JSON.stringify(v)).toBe(true);if(!v.ok)return;const p=prepareGeneration(v.value,request(t));expect(p.ok,JSON.stringify(p)).toBe(true);if(!p.ok)return;expect(validatePreparedInput(v.value,JSON.parse(JSON.stringify(p.value))).ok).toBe(true);const d=composeDocument(v.value,p.value);expect(d.ok,JSON.stringify(d)).toBe(true);if(!d.ok)return;const x:any=d.value;expect(x.nodes[x.rootIds[0]].children[0].text).toBe('BODY');expect(x.header.nodes[x.header.rootIds[0]].children[0].text).toBe('HEAD');expect(x.footer.nodes[x.footer.rootIds[0]].children[0].text).toBe('FOOT');expect(validateResolvedDocument(JSON.parse(JSON.stringify(x)))).toEqual([]);});
it('requires scoped values without borrowing body data',()=>{const t=bandTemplate(),v=validateTemplate(t);expect(v.ok).toBe(true);if(!v.ok)return;const r:any=request(t);delete r.header;const p=prepareGeneration(v.value,r);expect(p.ok).toBe(false);if(!p.ok)expect(p.issues.some(i=>i.path==='header.projectName')).toBe(true);});
it('validates one-level Columns and rejects ambiguous bands',()=>{const t=bandTemplate(),b=t.header;b.fragment.nodes.cols={id:'cols',type:'columns',props:{},columns:[{weight:1,childIds:['title']}]};b.fragment.rootIds=['cols'];expect(validateTemplate(t).ok).toBe(true);b.fragment.nodes.cols.columns[0].childIds=['cols'];expect(validateTemplate(t).ok).toBe(false);});
it.each(['legacy','style','sizing','local','toc','array'])('rejects invalid band %s',kind=>{const t=bandTemplate();if(kind==='legacy')t.nodeModelVersion=13;if(kind==='style')t.header.baseTextStyleId='missing';if(kind==='sizing')t.header.sizing={mode:'fixed',height:{value:1,unit:'pt'}};if(kind==='local')t.header.fragment.nodes.title.children[0].scope='local';if(kind==='toc')t.header.fragment.nodes.title.props.toc={level:1};if(kind==='array')t.header.inputSchema.fields.rows={type:'array',items:{type:'object',fields:{x:{type:'string'}}}};expect(validateTemplate(t).ok).toBe(false);});
it('uses optional defaults when a band object is omitted and keeps warnings scoped',()=>{const t=bandTemplate();t.header.inputSchema.fields.projectName={type:'string',default:'DEFAULT'};const v=validateTemplate(t);expect(v.ok).toBe(true);if(!v.ok)return;const r:any=request(t);delete r.header;r.footer.unknown='ignored';const p=prepareGeneration(v.value,r);expect(p.ok,JSON.stringify(p)).toBe(true);if(!p.ok)return;expect(p.value.header).toEqual({projectName:'DEFAULT'});expect(validatePreparedInput(v.value,p.value).ok).toBe(true);const forged=structuredClone(p.value);forged.header={projectName:12} as any;expect(validatePreparedInput(v.value,forged).ok).toBe(false);const d=composeDocument(v.value,p.value);if(!d.ok)throw Error(JSON.stringify(d));(d.value.header!.nodes[d.value.header!.rootIds[0]!] as any).props.toc={level:1};expect(validateResolvedDocument(d.value).length).toBeGreaterThan(0);});
